model:
    seq_length: 50
    state_input_dim: 95
    offset_input_dim: 91
    target_input_dim: 88
    lstm_dim: 768
    num_joints: 22
data:
    data_dir: 'D:\\ubisoft-laforge-animation-dataset\\lafan1\\lafan1'
    offsets: [
       [-42.198200,91.614723,-40.067841],
       [ 0.103456,1.857829,10.548506],
       [43.499992,-0.000038,-0.000002],
       [42.372192,0.000015,-0.000007],
       [ 17.299999,-0.000002,0.000003],
       [0.000000,0.000000,0.000000],

       [0.103457,1.857829,-10.548503],
       [43.500042,-0.000027,0.000008],
       [42.372257,-0.000008,0.000014],
       [17.299992,-0.000005,0.000004],
       [0.000000,0.000000,0.000000],

       [6.901968,-2.603733,-0.000001],
       [12.588099,0.000002,0.000000],
       [12.343206,0.000000,-0.000001],
       [25.832886,-0.000004,0.000003],
       [11.766620,0.000005,-0.000001],
       [0.000000,0.000000,0.000000],

       [19.745899,-1.480370,6.000108],
       [11.284125,-0.000009,-0.000018],
       [33.000050,0.000004,0.000032],
       [25.200008,0.000015,0.000008],
       [0.000000,0.000000,0.000000],

       [19.746099,-1.480375,-6.000073],
       [11.284138,-0.000015,-0.000012],
       [33.000092,0.000017,0.000013],
       [25.199780,0.000135,0.000422],
       [0.000000,0.000000,0.000000]
    ]
    parents: [-1,  0,  1,  2,  3,  4,
              0,  6,  7,  8,  9,
              0, 11, 12, 13, 14, 15,
              13, 17, 18, 19, 20, 
              13, 22, 23, 24, 25]
    joints_to_remove: [5,10,16,21,26]
    offset: 10
    num_workers: 4
test:
    batch_size: 32
    num_epoch: 1
    use_ztta: True
    use_adv: True
    save_img: True
    save_gif: True
    save_pose: False
    save_bvh: False
    debug: False
    version: ''
    model_dir: 'D:\\ubisoft-laforge-animation-dataset\\model\\2020-12-10-00_55_12-'
